services:
  keystore:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - KEYSTORE_TTL=600
    volumes:
      - ./data:/data
    command: ["./keystore", "http"]
