name: Arch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Keystore Docker image
      run: |
        docker build -t keystore:latest .

    - name: Run Keystore in container
      run: |
        docker run --rm keystore:latest ./keystore cli
